tipos = input('Digite alguma coisa :')
print('É alpha numerico ?',(tipos.isalnum()))
print('É alpha ?',(tipos.isalpha()))
print('É ASCII ?',(tipos.isascii()))
print('É decimal ?',(tipos.isdecimal()))
print('É um digito ?',(tipos.isdigit()))
print('É Identifier ?',(tipos.isidentifier()))
print('É Maiusculo ?',(tipos.isupper()))
print('É minusculo ?',(tipos.islower()))
print('É numerico ?',(tipos.isnumeric()))
print('É printavel ?',(tipos.isprintable()))
print('Tem espaço ? ',(tipos.isspace()))
print('É um Titulo ? ',(tipos.istitle()))
